### ISSUE TITLE
Header names with `-` result in invalid property names

### ISSUE THREAD

**Issue by egil** [atc-net/atc-rest-api-generator#94]
**Describe the bug**

When adding a header parameter to a spec with `-` characters in the name, the generated c# property in the parameters class is invalid.

**To Reproduce**

Example of a parameter that causes this:

```yaml
parameters:
  - name: x-on-behalf-of
    in: header
    description: 'The name of the user performing the operation.'
    required: false        
    schema:
      type: string
```

The generated output:

```c#
/// <summary>
/// The name of the user performing the operation.
/// </summary>
[FromHeader(Name = "x-on-behalf-of")]
public string X-on-behalf-of { get; set; }

/// <summary>
/// Converts to string.
/// </summary>
public override string ToString()
{
    return $"{nameof(AreaIdentifier)}: {AreaIdentifier}, {nameof(Id)}: {Id}, {nameof(X-on-behalf-of)}: {X-on-behalf-of}";
}
```

**Expected behavior**

Correct capitalization of the name and removal of the `-` character, similar to other parameters.

**Other considerations**

In the example above, the `x-on-behalf-of` header could be named `XOnBehalfOf`, but it would be great if the generator allowed us to specify a custom property name. This could be done with a through a [custom property](https://swagger.io/docs/specification/openapi-extensions/) in the spec, e.g. `x-generated-name: OnBehalfOf`, to make the generated code more usable. That feature could be generally useful in all places where we name things that are represented in code.
